# Pandas

데이터 프레임(통계관련 분야)을 생성해서 관리할 수 있는 패키지

In [1]:
import pandas as pd
import numpy as np

### 시리즈

데이터 프레임을 구성하는 특성 하나를 의미, 1차원 배열과 유사

In [2]:
# 리스트처럼 관리하는 것
data1 = [990232,344213,434323,323434]
s1 = pd.Series(data1)
s1

0    990232
1    344213
2    434323
3    323434
dtype: int64

In [36]:
data1 = [990232,344213,434323,323434]
index1 = ['서울', '부산', '인천', '대구']

In [37]:
# 딕셔너리와 유사하게 관리하겠다는 것
s2 = pd.Series(data1, index=index1)
s2

# 값만 추출
print(s2.values)
#인덱스만 추출
print(s2.index)

[990232 344213 434323 323434]
Index(['서울', '부산', '인천', '대구'], dtype='object')


In [5]:
# 시리즈의 이름을 셋팅한다
s2.name = '인구'
s2

서울    990232
부산    344213
인천    434323
대구    323434
Name: 인구, dtype: int64

In [6]:
# 시리즈 연산 ; numpy랑 같은
print(s2)
print(s2 + 329593)
print(s2 - 329593)
print(s2 * 155)
print(s2 // 16)

서울    990232
부산    344213
인천    434323
대구    323434
Name: 인구, dtype: int64
서울    1319825
부산     673806
인천     763916
대구     653027
Name: 인구, dtype: int64
서울    660639
부산     14620
인천    104730
대구     -6159
Name: 인구, dtype: int64
서울    153485960
부산     53353015
인천     67320065
대구     50132270
Name: 인구, dtype: int64
서울    61889
부산    21513
인천    27145
대구    20214
Name: 인구, dtype: int64


In [7]:
s2

서울    990232
부산    344213
인천    434323
대구    323434
Name: 인구, dtype: int64

In [8]:
print(s2[1])
print(s2['부산'])

344213
344213


In [9]:
# 다수의 값을 선택해서 가져온다
print(s2[[0,1,2]])
print(s2[['서울', '부산', '인천']])

서울    990232
부산    344213
인천    434323
Name: 인구, dtype: int64
서울    990232
부산    344213
인천    434323
Name: 인구, dtype: int64


In [10]:
print(s2[[2,0,1]])
print(s2[['인천', '서울', '부산']])

인천    434323
서울    990232
부산    344213
Name: 인구, dtype: int64
인천    434323
서울    990232
부산    344213
Name: 인구, dtype: int64


In [11]:
# True나 False가 들어있는 리스트, 배열(넘파이), 시리즈를 넣어주면 
# True에 해당하는 값들만 모아 새로운 시리즈로 생성

t1 = [True, False, True, False]
print(s1[t1])

0    990232
2    434323
dtype: int64


In [12]:
# 시리즈를 가지고 True나 False의 결과를 생성하는 수식을 넣어주면 시리즈 생성
# 이 시리즈를 넣어서 원하는 조건에 맞는 데이터만 가져올 수 있다
print(s2[s2 > 350000])

서울    990232
인천    434323
Name: 인구, dtype: int64


In [39]:
# 범위 지정
print(s2)

print('----------비교------------')
# 1 ~ 3-1까지
print(s2[1:3])
print('----------비교------------')
# 서울 ~ 인천까지(순서?)
print(s2['서울':'인천'])

서울    990232
부산    344213
인천    434323
대구    323434
dtype: int64
----------비교------------
부산    344213
인천    434323
dtype: int64
----------비교------------
서울    990232
부산    344213
인천    434323
dtype: int64


In [14]:
# 만약 시리즈의 인덱스가 문자열로 되어 있다면 .을 통해서 가져올 수도 있다
print(s2['서울'])
print(s2.서울)

990232
990232


In [15]:
# 시리즈의 인덱스가 숫자로 되어있다면??
data2 = [9902332,3442133,2434323,2323434]
s2 = pd.Series(data2)
s2

0    9902332
1    3442133
2    2434323
3    2323434
dtype: int64

In [16]:
for value in s2 :
    print(value)
    


9902332
3442133
2434323
2323434


In [17]:
# 시리즈의 인덱스가 문자열로 되어 있다면
data3 = [990232,344213,434323,323434]
index3 = ['서울', '부산', '인천', '대구']
s3 = pd.Series(data3, index=index3)
s3

서울    990232
부산    344213
인천    434323
대구    323434
dtype: int64

In [18]:
for value in s3 :
    print(value)

990232
344213
434323
323434


In [19]:
list(s3.items())

[('서울', 990232), ('부산', 344213), ('인천', 434323), ('대구', 323434)]

In [41]:
# 딕셔너리처럼 만들기
for key, value in s3.items() :
    print(key, value)

s9 = pd.Series([990232, 344213, 434323, 323434], index = ['서울', '부산', '인천', '대구'])

서울 990232
부산 344213
인천 434323
대구 323434


In [43]:
# 시리즈 생성하기
s10 = pd.Series([100, 200, 300, 400, 500], index = ['v1', 'v2', 'v3','v4','v5'])
print(s10)

v1    100
v2    200
v3    300
v4    400
v5    500
dtype: int64


In [22]:
s20 = pd.Series({'v1' : 100, 'v2' : 200, 'v3' : 300})
s20

v1    100
v2    200
v3    300
dtype: int64

In [23]:
s30 = pd.Series({'v1' : 100, 'v2' : 200, 'v3' : 300}, index = ['a1', 'a2', 'a3'])
s30

a1   NaN
a2   NaN
a3   NaN
dtype: float64

In [24]:
# index를 따로 세팅할 경우 세팅한 순서대로 시리즈가 만들어지며 존재하지 않는
# index는 결측치로 채워진다(NaN)
s30 = pd.Series({'v1' : 100, 'v2' : 200, 'v3' : 300}, index = ['v2', 'v3', 'v1'])
s30

v2    200
v3    300
v1    100
dtype: int64

In [44]:
### 시리즈 연산

s100 = pd.Series([10,20,30], index = ['a1', 'a2', 'a3'])
s200 = pd.Series([40,50,60], index = ['a2', 'a3', 'a4'])


In [26]:
print(s100)
print(s200)

a1    10
a2    20
a3    30
dtype: int64
a2    40
a3    50
a4    60
dtype: int64


In [27]:
# index가 다른 값들은 덧셈 연산에서 NaN 발생
r1 = s100 + s200
r1

a1     NaN
a2    60.0
a3    80.0
a4     NaN
dtype: float64

In [28]:
# index가 다른 값이더라도 Value만을 추출해서 덧셈 연산시킬 수 있음
r2 = s100.values + s200.values
print(s100.values)
print(s200.values)
print(r2)

[10 20 30]
[40 50 60]
[50 70 90]


In [29]:
s300 = pd.Series([10,20,30], index = ['a1', 'a2', 'a3'])
s400 = pd.Series([40,50], index = ['a1', 'a2'])
print(s300 + s400)
# 한쪽에만 있는 a3 가 연산 과정에서 결측치로 나옴

a1    50.0
a2    70.0
a3     NaN
dtype: float64


In [30]:
# .으로 조건 부가
(s300 + s400)[(s300 + s400).notnull()]

a1    50.0
a2    70.0
dtype: float64

In [47]:
# 출력 ; 조건으로 들어감
r100 = s300 + s400
print(r100[r100.notnull()])
print('----------------------')
# 출력; yes or no 문제
print(r100.notnull())
# 계산 후 결측치 부분을 제외하고 가져옴
print('----------------------')
print(r100.fillna(0))
# 계산 후 결측치 부분을 원하는 값으로 가져옴

a1    50.0
a2    70.0
dtype: float64
----------------------
a1     True
a2     True
a3    False
dtype: bool
----------------------
a1    50.0
a2    70.0
a3     0.0
dtype: float64


### 갱신, 추가, 삭제

In [32]:
s500 = pd.Series([10,20,30], index = ['v1', 'v2', 'v3'])
s500

v1    10
v2    20
v3    30
dtype: int64

In [33]:
s500['v1'] = 100
s500
# 원본 자체가 바뀌는 것

v1    100
v2     20
v3     30
dtype: int64

In [34]:
s500['v5'] = 600
s500
# 원본에 새로운 값을 추가

v1    100
v2     20
v3     30
v5    600
dtype: int64

In [35]:
del s500['v1']
s500
# 원본 값 삭제

v2     20
v3     30
v5    600
dtype: int64